### ISSUE TITLE
Camera goes crazy after creating new asset pack

### ISSUE THREAD

**Issue by abarmat** [decentraland/builder#700] opened 2019-09-23 00:32 UTC
**Steps to reproduce:**

1) Create a new Asset Pack on the sidebar
2) Import only ONE asset and set as ground
3) Finish the import process, save the asset pack

The camera goes loco

Attachment:
[Screen Recording 2019-09-20 at 15.54.14.mp4.zip](https://github.com/decentraland/builder/files/3640333/Screen.Recording.2019-09-20.at.15.54.14.mp4.zip)

**Comment by belohlavek** [comment] 2019-09-23 04:27
Can't reproduce :/

**Comment by nicosantangelo** [comment] 2019-09-24 20:15
Seems like it fixed itself™, closing to avoid clutter

**Closed by nicosantangelo** 2019-09-24 20:15 UTC
Labels: bug
